["server"]
  id = "1"
  port = 8080
  slaves = []
  exec_scripts = ["main"]

[["repos"]]
  name = "test"
  organization = "hamdy"
  git_base_url = "github.com"
  pull_interval = 300

[["repos"]]
  name = "example_trigger"
  organization = "threefoldtech"
  git_base_url = "github.com"
  pull_interval = 300

