["server"]
  id = "1"
  port = 8080
  slaves = []

[["repos"]]
  name = "test"
  url = "hamdy/test"
  pull_interval = 300
  startingpoint = "main"

[["repos"]]
  name = "example_trigger"
  url = "threefoldtech/example_trigger"
  pull_interval = 300
